_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      children: []
      layers:
      # radial symmetry. Creates terrain with radial symmetry around arbitrary point
      - sampling_function : mettagrid.map.scenes.simsam_functions.radial_symmetry 
        saturation: ${choose:1,2,3,4}
        function_parameters:
          x_zoom: ${uniform:0.05,0.2}
          y_zoom: ${uniform:0.05,0.2}
          angle_theta: ${uniform:0,1}
          symmetry: ${int:${uniform:2,9}}
          xc: ${triangular:-0.7,0.0,0.7}
          yc: ${triangular:-0.7,0.0,0.7}
      # random noise
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise 
        saturation: ${uniform:0.0,0.5}
        function_parameters:
          x_zoom: ${uniform:0.01,0.5}
          y_zoom: ${uniform:0.01,0.5}

      cutoff: ${uniform:0.02,0.63}
      force_seed: 0
