_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      children: []
      layers:
      # random noise
      - sampling_function : mettagrid.map.scenes.simsam_functions.squeezed_noise   
        saturation: ${uniform:1.0,2.0}
        function_parameters:
          zoom: ${uniform:0.1,1.25}
          squeeze: ${uniform:1,10} 
          angle_theta: ${uniform:0,1}
      # also random noise but smaller
      - sampling_function : mettagrid.map.scenes.simsam_functions.squeezed_noise   
        saturation: ${uniform:0.0,0.5}
        function_parameters:
          zoom: ${uniform:0.01,2.5}
          squeeze: ${uniform:1,10} 
          angle_theta: ${uniform:0,1}

      cutoff: ${uniform:0.15,0.40}
      force_seed: 0 