_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      children: []
      layers:
      # randomly rotated cross with random distortion alongside perpendicular axes
      - sampling_function : mettagrid.map.scenes.simsam_functions.cross_curse 
        saturation: ${choose:2,3}
        function_parameters:
          x_zoom: ${uniform:0.001,0.002} 
          y_zoom: ${uniform:0.001,0.002} 
          angle_theta: ${uniform:0,1} 
          x_pow: ${choose:0,2,3,4,5} 
          y_pow: ${choose:1,2,3,4,5} 
          xc: ${triangular:-0.6,0.0,0.6} 
          yc: ${triangular:-0.6,0.0,0.6} 
      # random noise
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise 
        saturation: ${uniform:0.0,1.5}
        function_parameters:
          x_zoom: ${uniform:0.01,0.5} 
          y_zoom: ${uniform:0.01,0.5} 

      cutoff: ${uniform:0.08,0.43}
      force_seed: NULL


