defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

# a single agent wanders around a square world with 10 rewards to find

num_agents: 1

# these are overwritten during training
progress:
  episode_count: 0
  mean_reward: 0.0
  last_mean_reward: 0.0
  last_difficulty: 0.0

# compute the ~10 episode running average 
filtered_mean_reward: ${iir:0.1,${.mean_reward},${.last_mean_reward}}

game:
  num_agents: ${..num_agents}
  # episode length 
  max_steps: 200

  difficulty_increase_threshold: 3.0
  should_increase_difficulty: ${gt:${..progress.mean_reward},${.difficulty_increase_threshold}}
  difficulty_increment: ${if:${.should_increase_difficulty},1.0,0.0}
  difficulty: ${add:${..progress.last_difficulty},${.difficulty_increment}}

  # scaling the map size as our experimental condition
  min_size: 10
  max_size: ${scale:${.difficulty},0,10,10,60,"log"}

  # for our experimental control, we will override max_size to always be 60

  size: ${make_integer:${uniform:${.min_size}, ${.max_size}}}

  map_builder:
    _target_: mettagrid.config.room.random.Random

    border_width: 6
    width: ${..size}
    height: ${..size}

    agents: ${..num_agents}

    objects:
      altar: 10

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: false
    get_items:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false

