defaults:
  - /env/mettagrid-base/mettagrid@
  - _self_

# a single agent wanders around a square world with 10 rewards to find

progress:
  episode_count: 0
  mean_reward: 0.0

num_agents: 1

min_size: 10

game:
  num_agents: ${..num_agents}

  # episode length 
  max_steps: 2000

  scaled_count: ${div:${..progress.episode_count},10}
 
  max_size: ${add:${..min_size}, ${clamp:${.scaled_count}, ${..min_size}, 60}}
  # max_size: 60

  size: ${make_integer:${uniform:${..min_size}, ${.max_size}}}

  map_builder:
    _target_: mettagrid.config.room.random.Random

    border_width: 6
    width: ${..size}
    height: ${..size}

    agents: ${..num_agents}

    objects:
      altar: 10

  actions:
    noop:
      enabled: true
    move:
      enabled: true
    rotate:
      enabled: true
    put_items:
      enabled: false
    get_items:
      enabled: true
    attack:
      enabled: false
    swap:
      enabled: false
    change_color:
      enabled: false

