_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      children: []
      layers:
      # over-complex sampler that produces interesting looking terrain
      - sampling_function : mettagrid.map.scenes.simsam_functions.the_sphere
        saturation: ${triangular:1,2,4}
        function_parameters:
          x_zoom: ${triangular:1,2,6}
          y_zoom: ${triangular:1,2,6}
          angle_theta: ${uniform:0,1}
          x_pow: ${choose:0,2,3,4,5} 
          y_pow: ${choose:1,2,3,4,5} 
          xc: ${triangular:-0.6,0.0,0.6}
          yc: ${triangular:-0.6,0.0,0.6}
          P: ${uniform:0.1,50}          
          ax: ${triangular:-3,0,3}      
          ay: ${triangular:-3,0,3}      
          bx: ${triangular:-4,0,4}      
          by: ${triangular:-4,0,4}      
      # random noise
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise
        saturation: ${uniform:0.0,1.5}
        function_parameters:
          x_zoom: ${uniform:0.01,0.5}
          y_zoom: ${uniform:0.01,0.5}

      cutoff: ${uniform:0.20,0.40}
      force_seed: 0