_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      children: []
      layers:
      # spiral sampler, twists the noise around arbitrary point
      # often creates terrain that requires to go in circles
      - sampling_function : mettagrid.map.scenes.simsam_functions.spiral 
        saturation: ${choose:1,2,3,4,5}
        function_parameters:
          zoom: ${uniform:0.01,0.2}
          squeeze: ${triangular:1,1,3}
          angle_theta: ${uniform:0,1}
          P: ${triangular:-10,0,10}
          xc: ${triangular:-0.6,0.0,0.6}
          yc: ${triangular:-0.6,0.0,0.6}
      # random noise
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise 
        saturation: ${uniform:0.0,0.5}
        function_parameters:
          x_zoom: ${uniform:0.01,0.5}
          y_zoom: ${uniform:0.01,0.5}

      cutoff: ${uniform:0.15,0.40}
      force_seed: 0

