# see reference_design.yaml for explanation of components

_target_: metta.agent.metta_agent.MettaAgent

defaults:
  - simple
  - _self_

components:
  _action_:
    _target_: metta.agent.lib.action.MettaActorBig
    bilinear_output_dim: 32
    mlp_hidden_dim: 512
    input_source: 
      - _core_
      - _action_embeds_
