# @package __global__

defaults:
  - override /agent: simple
  - override /eval: simple
  - override /analyzer: eval_analyzer
  - _self_

seed: null
run_id: 20250418.01
run: ${oc.env:USER}.local.${run_id}
trained_policy_uri: ./train_dir/${oc.env:USER}.local.${run_id}/checkpoints/

trainer:
  env: /env/mettagrid/robb_map
  # evaluate_interval must be >= checkpoint_interval = 300 on pufferbox
  evaluate_interval: ${.checkpoint_interval}
  evaluate: false

# passed to evaluation (and play) 
# either local or wandb if an aws run
# policy_uri: wandb://run/${.run}
policy_uri: ${.trained_policy_uri}

# location of output data for eval
eval_db_uri: null

analyzer:
  eval_stats_uri: ${run_dir}/eval_stats
  policy_uri: ${..policy_uri}
  analysis:
    metrics:
      - metric: episode_reward

eval:
  num_envs: 10 # evaluate over 10 iterations -- better stats
  num_episodes: 100
  max_time_s: 600
  env: ${..trainer.env}
  policy_uri: ${..policy_uri}
  eval_db_uri: ${..eval_db_uri}
